name: pipeline_f3uter_compare_3-seq
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - r-base=3.6.2
 - r-tidyverse
 - snakemake==5.32.2
 - bioconductor-derfinder
 - bioconductor-rtracklayer
 - bioconductor-AnnotationDbi
 - r-grid
 - r-tools
 - r-ggpubr
 - r-ROCR
 - r-caret
 - r-plotrix
 - r-PRROC
