name: pipeline_zebrafish_eval
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - r-base=3.6.2
 - r-tidyverse
 - snakemake==5.32.2
 - bioconductor-derfinder
 - bioconductor-BSgenome
 - bioconductor-rtracklayer
 - bioconductor-BSgenome.Drerio.UCSC.danRer10
 - bioconductor-TFBSTools
 - bioconductor-plyranges
 - r-scales
 - r-randomForest
 - r-ROCR
 - r-caret
 - r-e1071
 - r-PRROC
 - r-rlist
 - r-matrixStats
